# Generated by Django 4.1.13 on 2023-12-31 17:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('puissance', models.IntegerField()),
                ('longueur', models.CharField(max_length=100)),
                ('nbPlaces', models.IntegerField()),
                ('nbPortes', models.IntegerField()),
                ('couleur', models.CharField(max_length=100)),
                ('occasion', models.BooleanField()),
                ('prix', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colCatalogue',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=12)),
                ('taux', models.IntegerField()),
                ('situationFamiliale', models.CharField(max_length=20)),
                ('nbEnfantsAcharge', models.IntegerField()),
                ('deuxieme_voiture', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'colCategorieImmatriculations',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10)),
                ('taux', models.CharField(max_length=5000)),
                ('situationFamiliale', models.CharField(max_length=20)),
                ('nbEnfantsACharge', models.IntegerField()),
                ('deuxiemeVoiture', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'colClients',
            },
        ),
        migrations.CreateModel(
            name='Co2',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('modele', models.IntegerField()),
                ('bonusMalus', models.CharField(max_length=100)),
                ('rejetsCO2', models.CharField(max_length=100)),
                ('coutEnergie', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colCo2',
            },
        ),
        migrations.CreateModel(
            name='Immatriculations',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('puissance', models.IntegerField()),
                ('longueur', models.CharField(max_length=100)),
                ('nbPlaces', models.IntegerField()),
                ('nbPortes', models.IntegerField()),
                ('couleur', models.CharField(max_length=100)),
                ('occasion', models.BooleanField()),
                ('prix', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colImmatriculations',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
                ('taux', models.IntegerField()),
                ('situationFamiliale', models.CharField(max_length=20)),
                ('nbEnfantsACharge', models.IntegerField()),
                ('deuxiemeVoiture', models.BooleanField()),
            ],
            options={
                'db_table': 'colMarketing',
            },
        ),
    ]
